# -*- coding: utf-8 -*-
"""Faire trancher par le vrai slicer, en arrière-plan.

Emmanuel, 2026-09-30 : le temps et les grammes affichés par neoSlice sont
CALCULÉS. Les slicers savent travailler sans interface, pilotés par une ligne
de commande : on peut donc leur demander de trancher pour de vrai et lire les
valeurs qu'ils écrivent eux-mêmes.

Vérifié sur sa machine, sur un cube de 30 × 30 × 20 mm :

    PrusaSlicer     25 min   7,01 cm³   profil par défaut
    OrcaSlicer    1 h 05     6,60 cm³   X1C + Generic PLA
    Bambu Studio    53 min   6,10 cm³   X1C + Generic PLA

⚠ L'écart entre ces trois chiffres est le cœur du sujet : il FAUT trancher
avec le slicer et les profils de l'utilisateur. Afficher le temps de
PrusaSlicer à quelqu'un qui imprime sur une X1 Carbon serait plus faux que
l'estimation actuelle. D'où la règle du module : mieux vaut ne rien renvoyer
que renvoyer le chiffre d'un autre.

Les trois slicers n'écrivent pas la même chose, et c'est ce qui a demandé le
plus de mise au point :
  PrusaSlicer  « estimated printing time (normal mode) = 25m 19s » + cm³
  OrcaSlicer   « total estimated time: 21m 1s » EN TÊTE, cm³ TOUT À LA FIN
  Bambu Studio « total estimated time: 12m 50s » + longueur en mm, pas de cm³
"""
from pathlib import Path

import pytest

from core.slicing import lire_gcode, slicers_installes, trancher
from core.slicing.tranchage_reel import _duree_en_minutes, profils_orca

# ── Les trois dialectes de gcode ──────────────────────────────────────────
GCODE_PRUSA = """
; generated by PrusaSlicer
; filament used [mm] = 2916.08
; filament used [cm3] = 7.01
; total filament used [g] = 0.00
; estimated printing time (normal mode) = 25m 19s
"""

GCODE_ORCA_TETE = "; model printing time: 14m 27s; total estimated time: 21m 1s\n"
GCODE_ORCA_QUEUE = "; filament used [mm] = 2691.83\n; filament used [cm3] = 6.47\n"

GCODE_BAMBU = """
; model printing time: 12m 49s; total estimated time: 12m 50s
; total filament length [mm] : 2487.06
; total filament weight [g] : 0.00
"""


def test_le_dialecte_prusaslicer():
    minutes, volume, grammes = lire_gcode(GCODE_PRUSA)
    assert minutes == 25
    assert volume == pytest.approx(7.01)
    assert grammes == pytest.approx(7.01 * 1.24, rel=0.01)


def test_le_dialecte_orca_temps_en_tete_volume_en_queue():
    """Le piège qui a coûté un tour : Orca écrit le temps au tout début du
    fichier et le volume tout à la fin. Lire séparément les deux bouts ne
    donnait jamais les deux valeurs ensemble."""
    assert lire_gcode(GCODE_ORCA_TETE) is None, "la tête seule ne suffit pas"
    assert lire_gcode(GCODE_ORCA_QUEUE) is None, "la queue seule non plus"
    minutes, volume, _g = lire_gcode(GCODE_ORCA_TETE + GCODE_ORCA_QUEUE)
    assert minutes == 21
    assert volume == pytest.approx(6.47)


def test_le_dialecte_bambu_studio_ne_donne_que_la_longueur():
    """Bambu n'écrit pas de cm³. On repasse au volume par la section du fil."""
    minutes, volume, grammes = lire_gcode(GCODE_BAMBU)
    assert minutes == 13, "12 min 50 s s'arrondit à 13 minutes"
    # 2487,06 mm de fil de 1,75 mm font 5,98 cm³
    assert volume == pytest.approx(5.98, abs=0.05)
    assert grammes == pytest.approx(5.98 * 1.24, rel=0.02)


def test_un_diametre_de_fil_inhabituel_est_respecte():
    g = GCODE_BAMBU + "; filament_diameter = 2.85\n"
    _m, volume, _g = lire_gcode(g)
    assert volume == pytest.approx(2487.06 * 3.14159 * 1.425 ** 2 / 1000, rel=0.01)


def test_un_diametre_aberrant_est_ignore():
    """Un profil cassé ne doit pas produire un volume délirant."""
    g = GCODE_BAMBU + "; filament_diameter = 0\n"
    _m, volume, _g = lire_gcode(g)
    assert volume == pytest.approx(5.98, abs=0.05)


# ── Les durées ────────────────────────────────────────────────────────────
@pytest.mark.parametrize("texte,attendu", [
    ("25m 19s", 25), ("21m 1s", 21), ("1h 30m", 90), ("2h", 120),
    ("1d 2h 30m", 1590), ("45s", 1), ("3h 5m 20s", 185),
])
def test_les_durees_sont_comprises(texte, attendu):
    assert _duree_en_minutes(texte) == attendu


def test_une_duree_vide_ne_ment_pas():
    assert _duree_en_minutes("") is None
    assert _duree_en_minutes("tout de suite") is None


# ── La masse ──────────────────────────────────────────────────────────────
def test_la_masse_du_slicer_est_ignoree_quand_elle_vaut_zero():
    """Les trois slicers écrivent 0,00 g tant que le profil de filament ne
    porte pas de densité. On calcule donc la masse nous-mêmes."""
    _m, _v, grammes = lire_gcode(GCODE_PRUSA)
    assert grammes > 5.0


def test_la_densite_du_materiau_est_prise_en_compte():
    from core.slicing.tranchage_reel import DENSITES
    _m, _v, pla = lire_gcode(GCODE_PRUSA, densite=DENSITES["PLA"])
    _m, _v, tpu = lire_gcode(GCODE_PRUSA, densite=DENSITES["TPU"])
    assert pla != tpu and pla > tpu


def test_un_gcode_sans_rien_dedans_renvoie_None():
    assert lire_gcode("; juste des trajets\nG1 X1 Y1\n") is None


# ── La détection et le tranchage, sur la vraie machine ───────────────────
def _cube():
    """UN seul cube de référence, 30 × 30 × 20 mm, partagé par les tests.

    Deux tailles différentes sous le même nom de fichier faisaient passer des
    bornes écrites pour l'une et vérifiées sur l'autre.
    """
    import trimesh
    c = Path(__file__).parent / "_cube_tranchage_30x30x20.stl"
    if not c.exists():
        trimesh.creation.box(extents=(30, 30, 20)).export(c)
    return c



def test_la_detection_ne_renvoie_que_des_fichiers_reels():
    for s in slicers_installes():
        assert s.exe.is_file(), s.nom
        assert s.style in ("prusa", "orca")


def test_un_modele_inexistant_ne_fait_pas_tomber():
    liste = slicers_installes()
    if not liste:
        pytest.skip("aucun slicer installé")
    assert trancher(Path("nulle_part.stl"), liste[0]) is None


def test_un_slicer_de_la_famille_orca_refuse_sans_profils():
    """Sans machine ni process cohérents, Orca ne tranche pas. On ne lance
    même pas : un chiffre obtenu au hasard serait pire que pas de chiffre."""
    orca = [s for s in slicers_installes() if s.style == "orca"]
    if not orca:
        pytest.skip("aucun slicer de la famille Orca")
    assert trancher(_cube(), orca[0], profils=None) is None


def test_les_profils_choisis_sont_compatibles_entre_eux():
    """Le premier essai avait retenu un process « @BBL A1 » pour une X1
    Carbon, et le slicer refusait de travailler. La compatibilité est écrite
    dans les profils, on la lit au lieu de la deviner."""
    import json
    orca = [s for s in slicers_installes() if s.style == "orca"]
    if not orca:
        pytest.skip("aucun slicer de la famille Orca")
    for s in orca:
        p = profils_orca(s, "X1 Carbon", 0.4, 0.20, "PLA")
        if p is None:
            continue
        nom_machine = json.loads(p["machine"].read_text(encoding="utf-8"))["name"]
        for cle in ("process", "filament"):
            d = json.loads(p[cle].read_text(encoding="utf-8"))
            assert nom_machine in d.get("compatible_printers", []), (
                f"{s.nom} : {cle} {p[cle].stem} incompatible avec {nom_machine}")
        return
    pytest.skip("aucun profil X1 Carbon trouvé")


def test_le_tranchage_reel_donne_des_valeurs_credibles():
    """Bout en bout, avec un vrai slicer. Un cube de 30x30x20 mm ne peut pas
    s'imprimer en 2 minutes ni en 10 heures, ni consommer 1 g ni 200 g."""
    liste = slicers_installes()
    if not liste:
        pytest.skip("aucun slicer installé")
    cube = _cube()

    obtenus = []
    for s in liste:
        prof = profils_orca(s, "X1 Carbon", 0.4, 0.20, "PLA") if s.style == "orca" else None
        if s.style == "orca" and prof is None:
            continue
        r = trancher(cube, s, prof)
        if r is None:
            continue
        obtenus.append((s.nom, r))
        assert 5 <= r.minutes <= 600, f"{s.nom} : {r.minutes} min"
        assert 2.0 <= r.volume_cm3 <= 30.0, f"{s.nom} : {r.volume_cm3} cm³"
        assert 2.0 <= r.grammes <= 40.0, f"{s.nom} : {r.grammes} g"
        assert r.gcode.exists()
    if not obtenus:
        pytest.skip("aucun slicer n'a pu trancher sur cette machine")
