# -*- coding: utf-8 -*-
"""Textes de neoForge dans les 5 langues de neoSlice.

Ils vivent DANS le paquet téléchargé : une correction de formulation part par
une mise à jour du module, sans rebuild de neoSlice. La langue active est celle
de neoSlice (core.i18n.lang()).

Règle : chaque message dit ce qui se passe et quoi faire, jamais un code."""
from __future__ import annotations

FR = {
    "titre": "neoForge",
    "sous_titre": "modeleur 3D",

    # Barre d'outils
    "nouveau": "Nouveau",
    "ouvrir": "Ouvrir",
    "enregistrer": "Enregistrer",
    "annuler": "Annuler",
    "retablir": "Rétablir",
    "exporter": "Exporter",
    "envoyer": "Envoyer à neoSlice",
    "envoyer_info": "Envoie la pièce dans neoSlice pour l'optimiser et l'imprimer",

    # Écran d'accueil
    "accueil_titre": "Dessinez votre pièce",
    "accueil_texte": "Empilez des formes simples.",
    "accueil_nouveau": "Nouvelle pièce",
    "accueil_ouvrir": "Ouvrir un projet",
    "accueil_recents": "Projets récents",

    # Pile
    # La colonne de gauche ne montre plus des « étapes » mais les FORMES de la
    # scène, les arrondis ayant leur propre section (choix d'Emmanuel).
    "pile": "Formes",
    "arrondis": "Arrondis et découpes",
    "coupe": "Découpe",
    "ajouter_coupe": "Couper par un plan",
    "axe_coupe": "Couper selon",
    "position_coupe": "Position de la coupe",
    "garder_dessous": "Garder le dessous",
    "garder_dessus": "Garder le dessus",
    "garder_les_deux": "Garder les deux morceaux",
    "valider_coupe": "Valider la coupe",
    "partie_bas": "Partie du bas", "partie_haut": "Partie du haut",
    "partie_bas_fixe": "La partie du bas reste en place : déplacez celle du haut.",
    "coupe_sans_effet": "Le plan de coupe est hors de la pièce : rien n'est retiré.",
    "pile_vide": "Rien de sélectionné",
    "ajouter_forme": "Ajouter une forme",
    "ajouter_arrondi": "Arrondir des arêtes",
    "monter": "Monter",
    "descendre": "Descendre",
    "dupliquer": "Dupliquer",
    "supprimer": "Supprimer",
    "masquer": "Masquer cette étape",
    "montrer": "Remontrer cette étape",

    # Formes
    "cube": "Cube",
    "sphere": "Sphère",
    "cylindre": "Cylindre",
    "cone": "Cône",
    "tore": "Tore (anneau)",
    "coin": "Coin (rampe)",
    "prisme": "Prisme (polygone)",
    "logement_ecrou": "Logement d'écrou",
    "cotes_n": "{n} côtés",
    "nombre_cotes": "Nombre de côtés",
    "angle_pente": "Angle de la pente °",
    "matiere": "Ajouter de la matière",
    "creux": "Creuser",
    "intersection": "Garder l'intersection",
    "trou": "Trou traversant",

    # Propriétés
    "proprietes": "Réglages",
    "position": "Position",
    "dimensions": "Dimensions",
    "rotation": "Rotation",
    "diametre": "Diamètre",
    "descendue_pour_creuser": "Cette forme est passée sous la précédente : elle peut maintenant la creuser.",
    "mode_mesurer": "Mesurer",
    "regle_aide": "Cliquez un premier point, puis un second. La visée s'accroche aux coins, aux milieux et aux arêtes.",
    "centrer_plateau": "Centrer sur le plateau",
    "lier_xy_ferme": "Largeur et profondeur liées, la pièce reste ronde. Cliquez pour les régler séparément.",
    "lier_xy_ouvert": "Largeur et profondeur libres. Cliquez pour les lier et garder la pièce ronde.",
    "engrenage": "Engrenage",
    "nombre_dents": "Nombre de dents",
    "dents_n": "{n} dents",
    "profil_dents": "Profil des dents",
    "dent_droit": "Dents droites",
    "dent_arrondi": "Dents arrondies",
    "dent_pointu": "Dents pointues",
    "epaisseur_roue": "Épaisseur",
    "taraudage": "Trou taraudé",
    "trou_taraude": "Trou taraudé (vis)",
    "pas_de_vis": "Pas de vis",
    "profondeur_trou": "Profondeur",
    "cadre": "Cadre",
    "anneau": "Anneau",
    "epaisseur_bord": "Épaisseur du bord",
    "diametre_x": "Diamètre X",
    "diametre_y": "Diamètre Y",
    "diametre_bas": "Diamètre du bas",
    "diametre_tube": "Diamètre du tube",
    "diametre_haut": "Diamètre du haut",
    "hauteur": "Hauteur",
    "largeur": "Largeur",
    "profondeur": "Profondeur",
    "mode_taille": "Taille",
    "mode_deplacer": "Déplacer",
    "mode_tourner": "Tourner",
    "poser": "Poser sur ce qu'il y a dessous",
    "centrer": "Centrer sur la pièce du dessous",
    "collent": "Les pièces se collent",
    "traversent": "Les pièces se traversent",
    "deplacement_colle": "Arrêté au contact de la pièce voisine.",
    "cote_bloquee": "Dimension au minimum.",
    "rattache": "Pièce rattachée : elle suit désormais l'autre.",
    "detache": "Pièce détachée.",
    "lien_impossible": "Impossible : une pièce ne peut pas dépendre d'elle même.",
    "ne_touche_rien": "Cette forme ne touche aucune pièce : creuser ne retirera rien. Déplacez la dans la matière.",
    "premiere_matiere": "La première forme est toujours de la matière : il n'y a rien à creuser avant elle.",
    "verrouille": "Pièce soudée à son parent : tout l'ensemble bouge avec elle.",
    "deverrouille": "Pièce libérée : elle se règle maintenant toute seule.",
    "fermer_boite": "Fermer",
    "quitter_sans": "Ne pas enregistrer",
    "quitter_annuler": "Annuler",
    "restaurer_oui": "Reprendre",
    "restaurer_non": "Repartir de zéro",

    # Congés et chanfreins
    "arrondi": "Arrondi",
    "conge": "Congé (arrondi)",
    "chanfrein": "Chanfrein (biseau)",
    "taille_conge": "Rayon",
    "taille_chanfrein": "Largeur",
    "aretes": "Arêtes",
    "regle_toutes": "Toutes les arêtes",
    "regle_haut": "Les arêtes du haut",
    "regle_bas": "Les arêtes du bas",
    "regle_verticales": "Les arêtes verticales",
    "regle_liste": "Les arêtes choisies",
    "choisir_aretes": "Choisir les arêtes",
    "choisir_aretes_aide": "Cliquez les arêtes sur la pièce. Recliquez pour retirer.",
    "aretes_n": "{n} arête(s) choisie(s)",
    "termine": "Terminé",

    # Étapes en erreur
    "err_vide": "Cette étape ne laisse plus de matière.",
    "err_geometrie": "Cette forme n'a pas pu être calculée.",
    "err_rien_a_arrondir": "Il n'y a encore rien à arrondir : ajoutez une forme avant.",
    "err_aucune_arete": "Aucune arête ne correspond ici.",
    "err_introuvables": "Les arêtes choisies n'existent plus. Choisissez-les à nouveau.",
    "err_trop_grand": "Trop grand pour cette pièce.",
    "err_trop_grand_max": "Trop grand : {max} mm au maximum ici.",
    "aretes_manquantes": "{n} arête(s) n'ont pas été retrouvées.",

    # Calcul et état
    "calcul": "Calcul en cours…",
    "volume": "Volume {v} {u}",
    "taille_piece": "{x} × {y} × {z} {u}",
    "imprimante": "Imprimante : {nom}",
    "unite": "Unité", "unite_mm": "Millimètres (mm)",
    "unite_cm": "Centimètres (cm)", "unite_in": "Pouces (in)",

    # Imprimabilité
    "verif_ok": "Prête à imprimer.",
    "verif_ouverte": "La pièce n'est pas fermée : l'impression sera ratée.",
    "verif_trop_grande": "Trop grande pour le plateau ({x} × {y} × {z} mm pour {px} × {py} × {pz} mm).",
    "verif_morceaux": "La pièce est en {n} morceaux séparés.",
    "verif_trop_fine": "Un détail fait {mm} mm : trop fin pour être imprimé.",
    "exporter_quand_meme": "Exporter quand même",
    "corriger": "Corriger",
    "avert_titre": "Avant d'exporter",

    # Fichiers
    "projet_neoforge": "Projet neoForge (*.nfg)",
    "fichier_stl": "Fichier STL (*.stl)",
    "fichier_3mf": "Fichier 3MF (*.3mf)",
    "fichier_step": "Fichier STEP (*.step)",
    "enregistre": "Enregistré : {nom}",
    "exporte": "Exporté : {nom}",
    "ouverture_impossible": "Ce fichier n'a pas pu être ouvert.",
    "enregistrement_impossible": "Enregistrement impossible : {err}",
    "quitter_titre": "Quitter neoForge",
    "quitter_texte": "Votre pièce a changé depuis le dernier enregistrement. Enregistrer avant de fermer ?",
    "restaurer_titre": "Reprendre votre pièce",
    "restaurer_texte": "neoForge s'est fermé sans prévenir la dernière fois. Reprendre la pièce en cours ?",

    # Envoi vers neoSlice
    "envoi_ok": "Pièce envoyée à neoSlice.",
    "envoi_lancement": "Ouverture de neoSlice…",
    "envoi_echec": "neoSlice n'a pas répondu. Ouvrez neoSlice, puis réessayez.",
    "envoi_vide": "Il n'y a rien à envoyer.",
}

EN = {
    "titre": "neoForge",
    "sous_titre": "3D modeler",
    "nouveau": "New",
    "ouvrir": "Open",
    "enregistrer": "Save",
    "annuler": "Undo",
    "retablir": "Redo",
    "exporter": "Export",
    "envoyer": "Send to neoSlice",
    "envoyer_info": "Send the part to neoSlice to optimise and print it",
    "accueil_titre": "Design your part",
    "accueil_texte": "Stack simple shapes.",
    "accueil_nouveau": "New part",
    "accueil_ouvrir": "Open a project",
    "accueil_recents": "Recent projects",
    "pile": "Shapes",
    "arrondis": "Roundings and cuts",
    "coupe": "Cut",
    "ajouter_coupe": "Cut with a plane",
    "axe_coupe": "Cut along",
    "position_coupe": "Cut position",
    "garder_dessous": "Keep the lower part",
    "garder_dessus": "Keep the upper part",
    "garder_les_deux": "Keep both parts",
    "valider_coupe": "Apply the cut",
    "partie_bas": "Lower part", "partie_haut": "Upper part",
    "partie_bas_fixe": "The lower part stays put: move the upper one.",
    "coupe_sans_effet": "The cut plane is outside the part: nothing is removed.",
    "pile_vide": "Nothing selected",
    "ajouter_forme": "Add a shape",
    "ajouter_arrondi": "Round edges",
    "monter": "Move up",
    "descendre": "Move down",
    "dupliquer": "Duplicate",
    "supprimer": "Delete",
    "masquer": "Hide this step",
    "montrer": "Show this step again",
    "cube": "Cube",
    "sphere": "Sphere",
    "cylindre": "Cylinder",
    "cone": "Cone",
    "tore": "Torus (ring)",
    "coin": "Wedge (ramp)",
    "prisme": "Prism (polygon)",
    "logement_ecrou": "Nut pocket",
    "cotes_n": "{n} sides",
    "nombre_cotes": "Number of sides",
    "angle_pente": "Slope angle °",
    "matiere": "Add material",
    "creux": "Hollow out",
    "intersection": "Keep the intersection",
    "trou": "Through hole",
    "proprietes": "Settings",
    "position": "Position",
    "dimensions": "Dimensions",
    "rotation": "Rotation",
    "diametre": "Diameter",
    "descendue_pour_creuser": "This shape moved below the previous one, so it can now cut into it.",
    "mode_mesurer": "Measure",
    "regle_aide": "Click a first point, then a second. Aiming snaps to corners, midpoints and edges.",
    "centrer_plateau": "Centre on the plate",
    "lier_xy_ferme": "Width and depth linked, the part stays round. Click to set them separately.",
    "lier_xy_ouvert": "Width and depth independent. Click to link them and keep the part round.",
    "engrenage": "Gear",
    "nombre_dents": "Number of teeth",
    "dents_n": "{n} teeth",
    "profil_dents": "Tooth shape",
    "dent_droit": "Straight teeth",
    "dent_arrondi": "Rounded teeth",
    "dent_pointu": "Pointed teeth",
    "epaisseur_roue": "Thickness",
    "taraudage": "Threaded hole",
    "trou_taraude": "Threaded hole (screw)",
    "pas_de_vis": "Thread pitch",
    "profondeur_trou": "Depth",
    "cadre": "Frame",
    "anneau": "Ring",
    "epaisseur_bord": "Border thickness",
    "diametre_x": "Diameter X",
    "diametre_y": "Diameter Y",
    "diametre_bas": "Bottom diameter",
    "diametre_tube": "Tube diameter",
    "diametre_haut": "Top diameter",
    "hauteur": "Height",
    "largeur": "Width",
    "profondeur": "Depth",
    "mode_taille": "Size",
    "mode_deplacer": "Move",
    "mode_tourner": "Rotate",
    "poser": "Drop onto what is below",
    "centrer": "Center on the part below",
    "collent": "Parts snap together",
    "traversent": "Parts pass through",
    "deplacement_colle": "Stopped against the neighbouring part.",
    "cote_bloquee": "Dimension at its minimum.",
    "rattache": "Part attached: it now follows the other one.",
    "detache": "Part detached.",
    "lien_impossible": "Not possible: a part cannot depend on itself.",
    "ne_touche_rien": "This shape touches no part: hollowing will remove nothing. Move it into the material.",
    "premiere_matiere": "The first shape is always material: there is nothing to hollow before it.",
    "verrouille": "Part welded to its parent: the whole assembly moves with it.",
    "deverrouille": "Part released: it can now be adjusted on its own.",
    "fermer_boite": "Close",
    "quitter_sans": "Don't save",
    "quitter_annuler": "Cancel",
    "restaurer_oui": "Resume",
    "restaurer_non": "Start fresh",
    "arrondi": "Rounding",
    "conge": "Fillet (rounded)",
    "chanfrein": "Chamfer (bevel)",
    "taille_conge": "Radius",
    "taille_chanfrein": "Width",
    "aretes": "Edges",
    "regle_toutes": "All edges",
    "regle_haut": "Top edges",
    "regle_bas": "Bottom edges",
    "regle_verticales": "Vertical edges",
    "regle_liste": "Chosen edges",
    "choisir_aretes": "Choose edges",
    "choisir_aretes_aide": "Click edges on the part. Click again to remove.",
    "aretes_n": "{n} edge(s) chosen",
    "termine": "Done",
    "err_vide": "This step leaves no material.",
    "err_geometrie": "This shape could not be computed.",
    "err_rien_a_arrondir": "Nothing to round yet: add a shape first.",
    "err_aucune_arete": "No edge matches here.",
    "err_introuvables": "The chosen edges no longer exist. Please choose them again.",
    "err_trop_grand": "Too large for this part.",
    "err_trop_grand_max": "Too large: {max} mm maximum here.",
    "aretes_manquantes": "{n} edge(s) could not be found again.",
    "calcul": "Computing…",
    "volume": "Volume {v} {u}",
    "taille_piece": "{x} × {y} × {z} {u}",
    "imprimante": "Printer: {nom}",
    "unite": "Unit", "unite_mm": "Millimeters (mm)",
    "unite_cm": "Centimeters (cm)", "unite_in": "Inches (in)",
    "verif_ok": "Ready to print.",
    "verif_ouverte": "The part is not closed: the print will fail.",
    "verif_trop_grande": "Too large for the bed ({x} × {y} × {z} mm for {px} × {py} × {pz} mm).",
    "verif_morceaux": "The part is in {n} separate pieces.",
    "verif_trop_fine": "A detail is {mm} mm: too thin to print.",
    "exporter_quand_meme": "Export anyway",
    "corriger": "Fix it",
    "avert_titre": "Before exporting",
    "projet_neoforge": "neoForge project (*.nfg)",
    "fichier_stl": "STL file (*.stl)",
    "fichier_3mf": "3MF file (*.3mf)",
    "fichier_step": "STEP file (*.step)",
    "enregistre": "Saved: {nom}",
    "exporte": "Exported: {nom}",
    "ouverture_impossible": "This file could not be opened.",
    "enregistrement_impossible": "Could not save: {err}",
    "quitter_titre": "Quit neoForge",
    "quitter_texte": "Your part changed since the last save. Save before closing?",
    "restaurer_titre": "Resume your part",
    "restaurer_texte": "neoForge closed unexpectedly last time. Resume the part in progress?",
    "envoi_ok": "Part sent to neoSlice.",
    "envoi_lancement": "Opening neoSlice…",
    "envoi_echec": "neoSlice did not answer. Open neoSlice, then try again.",
    "envoi_vide": "There is nothing to send.",
}

ES = dict(EN, **{
    "sous_titre": "modelador 3D",
    "nouveau": "Nuevo", "ouvrir": "Abrir", "enregistrer": "Guardar",
    "annuler": "Deshacer", "retablir": "Rehacer", "exporter": "Exportar",
    "envoyer": "Enviar a neoSlice",
    "envoyer_info": "Envía la pieza a neoSlice para optimizarla e imprimirla",
    "accueil_titre": "Diseña tu pieza",
    "accueil_texte": "Apila formas simples.",
    "accueil_nouveau": "Pieza nueva",
    "accueil_ouvrir": "Abrir un proyecto", "accueil_recents": "Proyectos recientes",
    "collent": "Las piezas se pegan", "traversent": "Las piezas se atraviesan",
    "deplacement_colle": "Detenido al tocar la pieza vecina.",
    "cote_bloquee": "Dimensión en su mínimo.",
    "rattache": "Pieza vinculada: ahora sigue a la otra.",
    "detache": "Pieza desvinculada.",
    "lien_impossible": "Imposible: una pieza no puede depender de sí misma.",
    "ne_touche_rien": "Esta forma no toca ninguna pieza: vaciar no quitará nada. Muévela dentro del material.",
    "premiere_matiere": "La primera forma siempre es material: no hay nada que vaciar antes de ella.",
    "verrouille": "Pieza soldada a su padre: todo el conjunto se mueve con ella.",
    "deverrouille": "Pieza liberada: ahora se ajusta por separado.",
    "fermer_boite": "Cerrar",
    "quitter_sans": "No guardar",
    "quitter_annuler": "Cancelar",
    "restaurer_oui": "Retomar",
    "restaurer_non": "Empezar de cero",
    "pile": "Formas", "arrondis": "Redondeos y cortes",
    "coupe": "Corte", "ajouter_coupe": "Cortar con un plano",
    "axe_coupe": "Cortar según", "position_coupe": "Posición del corte",
    "garder_dessous": "Conservar la parte inferior",
    "garder_dessus": "Conservar la parte superior",
    "garder_les_deux": "Conservar las dos partes",
    "valider_coupe": "Aplicar el corte",
    "partie_bas": "Parte inferior", "partie_haut": "Parte superior",
    "partie_bas_fixe": "La parte inferior no se mueve: desplaza la superior.",
    "coupe_sans_effet": "El plano de corte está fuera de la pieza: no se quita nada.",
    "pile_vide": "Nada seleccionado", "ajouter_forme": "Añadir una forma",
    "ajouter_arrondi": "Redondear aristas", "monter": "Subir", "descendre": "Bajar",
    "dupliquer": "Duplicar", "supprimer": "Eliminar", "masquer": "Ocultar este paso",
    "montrer": "Mostrar de nuevo este paso",
    "cube": "Cubo", "sphere": "Esfera", "cylindre": "Cilindro", "cone": "Cono",
    "tore": "Toro (anillo)", "coin": "Cuña (rampa)", "prisme": "Prisma (polígono)",
    "logement_ecrou": "Alojamiento de tuerca",
    "cotes_n": "{n} lados", "nombre_cotes": "Número de lados",
    "angle_pente": "Ángulo de la pendiente °",
    "matiere": "Añadir material", "creux": "Vaciar",
    "intersection": "Conservar la intersección", "trou": "Agujero pasante",
    "proprietes": "Ajustes", "position": "Posición", "dimensions": "Dimensiones",
    "rotation": "Rotación", "descendue_pour_creuser": "Esta forma ha pasado debajo de la anterior: ya puede vaciarla.",
    "mode_mesurer": "Medir", "regle_aide": "Haga clic en un primer punto y luego en un segundo.",
    "centrer_plateau": "Centrar en la bandeja",
    "lier_xy_ferme": "Ancho y profundidad enlazados: la pieza sigue redonda.",
    "lier_xy_ouvert": "Ancho y profundidad independientes.",
    "engrenage": "Engranaje", "nombre_dents": "Número de dientes",
    "dents_n": "{n} dientes", "profil_dents": "Perfil de los dientes",
    "dent_droit": "Dientes rectos", "dent_arrondi": "Dientes redondeados",
    "dent_pointu": "Dientes puntiagudos", "epaisseur_roue": "Grosor",
    "taraudage": "Agujero roscado", "trou_taraude": "Agujero roscado (tornillo)",
    "pas_de_vis": "Paso de rosca", "profondeur_trou": "Profundidad",
    "cadre": "Marco", "anneau": "Anillo", "epaisseur_bord": "Grosor del borde",
    "diametre": "Diámetro", "diametre_x": "Diámetro X", "diametre_y": "Diámetro Y", "diametre_bas": "Diámetro inferior",
    "diametre_tube": "Diámetro del tubo",
    "diametre_haut": "Diámetro superior", "hauteur": "Altura", "largeur": "Ancho",
    "profondeur": "Profundidad",
    "mode_taille": "Tamaño", "mode_deplacer": "Mover", "mode_tourner": "Girar",
    "poser": "Apoyar sobre lo que hay debajo",
    "centrer": "Centrar sobre la pieza de abajo",
    "arrondi": "Redondeo", "conge": "Redondeo (curvo)", "chanfrein": "Chaflán (bisel)",
    "taille_conge": "Radio", "taille_chanfrein": "Ancho", "aretes": "Aristas",
    "regle_toutes": "Todas las aristas", "regle_haut": "Las aristas superiores",
    "regle_bas": "Las aristas inferiores", "regle_verticales": "Las aristas verticales",
    "regle_liste": "Las aristas elegidas", "choisir_aretes": "Elegir aristas",
    "choisir_aretes_aide": "Haz clic en las aristas de la pieza. Vuelve a hacer clic para quitarlas.",
    "aretes_n": "{n} arista(s) elegida(s)", "termine": "Listo",
    "err_vide": "Este paso no deja material.",
    "err_geometrie": "No se pudo calcular esta forma.",
    "err_rien_a_arrondir": "Todavía no hay nada que redondear: añade una forma antes.",
    "err_aucune_arete": "Ninguna arista coincide aquí.",
    "err_introuvables": "Las aristas elegidas ya no existen. Elígelas de nuevo.",
    "err_trop_grand": "Demasiado grande para esta pieza.",
    "err_trop_grand_max": "Demasiado grande: aquí como máximo {max} mm.",
    "aretes_manquantes": "No se han vuelto a encontrar {n} arista(s).",
    "calcul": "Calculando…", "volume": "Volumen {v} {u}",
    "imprimante": "Impresora: {nom}",
    "unite": "Unidad", "unite_mm": "Milímetros (mm)",
    "unite_cm": "Centímetros (cm)", "unite_in": "Pulgadas (in)",
    "verif_ok": "Lista para imprimir.",
    "verif_ouverte": "La pieza no está cerrada: la impresión fallará.",
    "verif_trop_grande": "Demasiado grande para la base ({x} × {y} × {z} mm para {px} × {py} × {pz} mm).",
    "verif_morceaux": "La pieza está en {n} trozos separados.",
    "verif_trop_fine": "Un detalle mide {mm} mm: demasiado fino para imprimirse.",
    "exporter_quand_meme": "Exportar igualmente", "corriger": "Corregir",
    "avert_titre": "Antes de exportar",
    "projet_neoforge": "Proyecto neoForge (*.nfg)", "fichier_stl": "Archivo STL (*.stl)",
    "fichier_3mf": "Archivo 3MF (*.3mf)", "fichier_step": "Archivo STEP (*.step)",
    "enregistre": "Guardado: {nom}", "exporte": "Exportado: {nom}",
    "ouverture_impossible": "No se pudo abrir este archivo.",
    "enregistrement_impossible": "No se pudo guardar: {err}",
    "quitter_titre": "Salir de neoForge",
    "quitter_texte": "Tu pieza ha cambiado desde el último guardado. ¿Guardar antes de cerrar?",
    "restaurer_titre": "Retomar tu pieza",
    "restaurer_texte": "neoForge se cerró de forma inesperada la última vez. ¿Retomar la pieza en curso?",
    "envoi_ok": "Pieza enviada a neoSlice.", "envoi_lancement": "Abriendo neoSlice…",
    "envoi_echec": "neoSlice no respondió. Abre neoSlice y vuelve a intentarlo.",
    "envoi_vide": "No hay nada que enviar.",
})

DE = dict(EN, **{
    "sous_titre": "3D-Modellierer",
    "nouveau": "Neu", "ouvrir": "Öffnen", "enregistrer": "Speichern",
    "annuler": "Rückgängig", "retablir": "Wiederholen", "exporter": "Exportieren",
    "envoyer": "An neoSlice senden",
    "envoyer_info": "Sendet das Teil an neoSlice, um es zu optimieren und zu drucken",
    "accueil_titre": "Entwerfen Sie Ihr Teil",
    "accueil_texte": "Stapeln Sie einfache Formen.",
    "accueil_nouveau": "Neues Teil",
    "accueil_ouvrir": "Projekt öffnen", "accueil_recents": "Zuletzt verwendet",
    "collent": "Teile rasten aneinander", "traversent": "Teile durchdringen sich",
    "deplacement_colle": "Am Nachbarteil gestoppt.",
    "cote_bloquee": "Maß am Minimum.",
    "rattache": "Teil verbunden: es folgt jetzt dem anderen.",
    "detache": "Teil gelöst.",
    "lien_impossible": "Nicht möglich: ein Teil kann nicht von sich selbst abhängen.",
    "ne_touche_rien": "Diese Form berührt kein Teil: Aushöhlen entfernt nichts. Schieben Sie sie ins Material.",
    "premiere_matiere": "Die erste Form ist immer Material: davor gibt es nichts auszuhöhlen.",
    "verrouille": "Teil fest verbunden: die ganze Baugruppe bewegt sich mit.",
    "deverrouille": "Teil gelöst: es lässt sich nun einzeln einstellen.",
    "fermer_boite": "Schließen",
    "quitter_sans": "Nicht speichern",
    "quitter_annuler": "Abbrechen",
    "restaurer_oui": "Fortsetzen",
    "restaurer_non": "Neu beginnen",
    "pile": "Formen", "arrondis": "Rundungen und Schnitte",
    "coupe": "Schnitt", "ajouter_coupe": "Mit einer Ebene schneiden",
    "axe_coupe": "Schneiden entlang", "position_coupe": "Schnittposition",
    "garder_dessous": "Unteren Teil behalten",
    "garder_dessus": "Oberen Teil behalten",
    "garder_les_deux": "Beide Teile behalten",
    "valider_coupe": "Schnitt übernehmen",
    "partie_bas": "Unteres Teil", "partie_haut": "Oberes Teil",
    "partie_bas_fixe": "Das untere Teil bleibt an Ort und Stelle: bewegen Sie das obere.",
    "coupe_sans_effet": "Die Schnittebene liegt außerhalb des Teils: nichts wird entfernt.",
    "pile_vide": "Nichts ausgewählt", "ajouter_forme": "Form hinzufügen",
    "ajouter_arrondi": "Kanten runden", "monter": "Nach oben", "descendre": "Nach unten",
    "dupliquer": "Duplizieren", "supprimer": "Löschen", "masquer": "Diesen Schritt ausblenden",
    "montrer": "Diesen Schritt wieder anzeigen",
    "cube": "Würfel", "sphere": "Kugel", "cylindre": "Zylinder", "cone": "Kegel",
    "tore": "Torus (Ring)", "coin": "Keil (Rampe)", "prisme": "Prisma (Vieleck)",
    "logement_ecrou": "Mutterntasche",
    "cotes_n": "{n} Seiten", "nombre_cotes": "Anzahl Seiten",
    "angle_pente": "Neigungswinkel °",
    "matiere": "Material hinzufügen", "creux": "Aushöhlen",
    "intersection": "Schnittmenge behalten", "trou": "Durchgangsloch",
    "proprietes": "Einstellungen", "position": "Position", "dimensions": "Maße",
    "rotation": "Drehung", "descendue_pour_creuser": "Diese Form liegt jetzt unter der vorherigen und kann sie aushöhlen.",
    "mode_mesurer": "Messen", "regle_aide": "Klicken Sie einen ersten Punkt an, dann einen zweiten.",
    "centrer_plateau": "Auf dem Druckbett zentrieren",
    "lier_xy_ferme": "Breite und Tiefe verbunden: das Teil bleibt rund.",
    "lier_xy_ouvert": "Breite und Tiefe unabhängig.",
    "engrenage": "Zahnrad", "nombre_dents": "Zähnezahl",
    "dents_n": "{n} Zähne", "profil_dents": "Zahnform",
    "dent_droit": "Gerade Zähne", "dent_arrondi": "Abgerundete Zähne",
    "dent_pointu": "Spitze Zähne", "epaisseur_roue": "Dicke",
    "taraudage": "Gewindeloch", "trou_taraude": "Gewindeloch (Schraube)",
    "pas_de_vis": "Gewindesteigung", "profondeur_trou": "Tiefe",
    "cadre": "Rahmen", "anneau": "Ring", "epaisseur_bord": "Randstärke",
    "diametre": "Durchmesser", "diametre_x": "Durchmesser X", "diametre_y": "Durchmesser Y", "diametre_bas": "Durchmesser unten",
    "diametre_tube": "Rohrdurchmesser",
    "diametre_haut": "Durchmesser oben", "hauteur": "Höhe", "largeur": "Breite",
    "profondeur": "Tiefe",
    "mode_taille": "Größe", "mode_deplacer": "Bewegen", "mode_tourner": "Drehen",
    "poser": "Auf das darunter absetzen",
    "centrer": "Auf dem Teil darunter zentrieren",
    "arrondi": "Rundung", "conge": "Verrundung", "chanfrein": "Fase",
    "taille_conge": "Radius", "taille_chanfrein": "Breite", "aretes": "Kanten",
    "regle_toutes": "Alle Kanten", "regle_haut": "Die oberen Kanten",
    "regle_bas": "Die unteren Kanten", "regle_verticales": "Die senkrechten Kanten",
    "regle_liste": "Die gewählten Kanten", "choisir_aretes": "Kanten wählen",
    "choisir_aretes_aide": "Kanten am Teil anklicken. Erneut klicken entfernt sie.",
    "aretes_n": "{n} Kante(n) gewählt", "termine": "Fertig",
    "err_vide": "Dieser Schritt lässt kein Material übrig.",
    "err_geometrie": "Diese Form konnte nicht berechnet werden.",
    "err_rien_a_arrondir": "Noch nichts zum Runden: fügen Sie zuerst eine Form hinzu.",
    "err_aucune_arete": "Hier passt keine Kante.",
    "err_introuvables": "Die gewählten Kanten gibt es nicht mehr. Bitte erneut wählen.",
    "err_trop_grand": "Zu groß für dieses Teil.",
    "err_trop_grand_max": "Zu groß: hier höchstens {max} mm.",
    "aretes_manquantes": "{n} Kante(n) wurden nicht wiedergefunden.",
    "calcul": "Berechnung…", "volume": "Volumen {v} {u}",
    "imprimante": "Drucker: {nom}",
    "unite": "Einheit", "unite_mm": "Millimeter (mm)",
    "unite_cm": "Zentimeter (cm)", "unite_in": "Zoll (in)",
    "verif_ok": "Druckbereit.",
    "verif_ouverte": "Das Teil ist nicht geschlossen: der Druck wird misslingen.",
    "verif_trop_grande": "Zu groß für das Druckbett ({x} × {y} × {z} mm für {px} × {py} × {pz} mm).",
    "verif_morceaux": "Das Teil besteht aus {n} getrennten Stücken.",
    "verif_trop_fine": "Ein Detail misst {mm} mm: zu dünn zum Drucken.",
    "exporter_quand_meme": "Trotzdem exportieren", "corriger": "Korrigieren",
    "avert_titre": "Vor dem Export",
    "projet_neoforge": "neoForge-Projekt (*.nfg)", "fichier_stl": "STL-Datei (*.stl)",
    "fichier_3mf": "3MF-Datei (*.3mf)", "fichier_step": "STEP-Datei (*.step)",
    "enregistre": "Gespeichert: {nom}", "exporte": "Exportiert: {nom}",
    "ouverture_impossible": "Diese Datei konnte nicht geöffnet werden.",
    "enregistrement_impossible": "Speichern nicht möglich: {err}",
    "quitter_titre": "neoForge beenden",
    "quitter_texte": "Ihr Teil hat sich seit dem letzten Speichern geändert. Vor dem Schließen speichern?",
    "restaurer_titre": "Teil fortsetzen",
    "restaurer_texte": "neoForge wurde letztes Mal unerwartet beendet. Das laufende Teil fortsetzen?",
    "envoi_ok": "Teil an neoSlice gesendet.", "envoi_lancement": "neoSlice wird geöffnet…",
    "envoi_echec": "neoSlice hat nicht geantwortet. Öffnen Sie neoSlice und versuchen Sie es erneut.",
    "envoi_vide": "Es gibt nichts zu senden.",
})

IT = dict(EN, **{
    "sous_titre": "modellatore 3D",
    "nouveau": "Nuovo", "ouvrir": "Apri", "enregistrer": "Salva",
    "annuler": "Annulla", "retablir": "Ripristina", "exporter": "Esporta",
    "envoyer": "Invia a neoSlice",
    "envoyer_info": "Invia il pezzo a neoSlice per ottimizzarlo e stamparlo",
    "accueil_titre": "Disegna il tuo pezzo",
    "accueil_texte": "Impila forme semplici.",
    "accueil_nouveau": "Nuovo pezzo",
    "accueil_ouvrir": "Apri un progetto", "accueil_recents": "Progetti recenti",
    "collent": "I pezzi si incollano", "traversent": "I pezzi si compenetrano",
    "deplacement_colle": "Fermato a contatto con il pezzo vicino.",
    "cote_bloquee": "Dimensione al minimo.",
    "rattache": "Pezzo collegato: ora segue l'altro.",
    "detache": "Pezzo scollegato.",
    "lien_impossible": "Impossibile: un pezzo non può dipendere da se stesso.",
    "ne_touche_rien": "Questa forma non tocca nessun pezzo: scavare non toglierà nulla. Spostala nella materia.",
    "premiere_matiere": "La prima forma è sempre materia: non c'è nulla da scavare prima di lei.",
    "verrouille": "Pezzo saldato al genitore: tutto l'insieme si muove con lui.",
    "deverrouille": "Pezzo liberato: ora si regola da solo.",
    "fermer_boite": "Chiudi",
    "quitter_sans": "Non salvare",
    "quitter_annuler": "Annulla",
    "restaurer_oui": "Riprendi",
    "restaurer_non": "Ricominciare",
    "pile": "Forme", "arrondis": "Arrotondamenti e tagli",
    "coupe": "Taglio", "ajouter_coupe": "Taglia con un piano",
    "axe_coupe": "Taglia lungo", "position_coupe": "Posizione del taglio",
    "garder_dessous": "Tenere la parte inferiore",
    "garder_dessus": "Tenere la parte superiore",
    "garder_les_deux": "Tenere entrambe le parti",
    "valider_coupe": "Applica il taglio",
    "partie_bas": "Parte inferiore", "partie_haut": "Parte superiore",
    "partie_bas_fixe": "La parte inferiore resta ferma: sposta quella superiore.",
    "coupe_sans_effet": "Il piano di taglio è fuori dal pezzo: non viene tolto nulla.",
    "pile_vide": "Niente selezionato", "ajouter_forme": "Aggiungi una forma",
    "ajouter_arrondi": "Arrotonda spigoli", "monter": "Sposta su", "descendre": "Sposta giù",
    "dupliquer": "Duplica", "supprimer": "Elimina", "masquer": "Nascondi questo passaggio",
    "montrer": "Mostra di nuovo questo passaggio",
    "cube": "Cubo", "sphere": "Sfera", "cylindre": "Cilindro", "cone": "Cono",
    "tore": "Toro (anello)", "coin": "Cuneo (rampa)", "prisme": "Prisma (poligono)",
    "logement_ecrou": "Alloggiamento dado",
    "cotes_n": "{n} lati", "nombre_cotes": "Numero di lati",
    "angle_pente": "Angolo della pendenza °",
    "matiere": "Aggiungi materiale", "creux": "Svuota",
    "intersection": "Mantieni l'intersezione", "trou": "Foro passante",
    "proprietes": "Impostazioni", "position": "Posizione", "dimensions": "Dimensioni",
    "rotation": "Rotazione", "descendue_pour_creuser": "Questa forma è passata sotto la precedente: ora può scavarla.",
    "mode_mesurer": "Misura", "regle_aide": "Fare clic su un primo punto, poi su un secondo.",
    "centrer_plateau": "Centra sul piano",
    "lier_xy_ferme": "Larghezza e profondità collegate: il pezzo resta rotondo.",
    "lier_xy_ouvert": "Larghezza e profondità indipendenti.",
    "engrenage": "Ingranaggio", "nombre_dents": "Numero di denti",
    "dents_n": "{n} denti", "profil_dents": "Profilo dei denti",
    "dent_droit": "Denti dritti", "dent_arrondi": "Denti arrotondati",
    "dent_pointu": "Denti appuntiti", "epaisseur_roue": "Spessore",
    "taraudage": "Foro filettato", "trou_taraude": "Foro filettato (vite)",
    "pas_de_vis": "Passo della filettatura", "profondeur_trou": "Profondità",
    "cadre": "Cornice", "anneau": "Anello", "epaisseur_bord": "Spessore del bordo",
    "diametre": "Diametro", "diametre_x": "Diametro X", "diametre_y": "Diametro Y", "diametre_bas": "Diametro inferiore",
    "diametre_tube": "Diametro del tubo",
    "diametre_haut": "Diametro superiore", "hauteur": "Altezza", "largeur": "Larghezza",
    "profondeur": "Profondità",
    "mode_taille": "Dimensione", "mode_deplacer": "Sposta", "mode_tourner": "Ruota",
    "poser": "Appoggia su ciò che sta sotto",
    "centrer": "Centra sul pezzo sottostante",
    "arrondi": "Arrotondamento", "conge": "Raccordo (arrotondato)", "chanfrein": "Smusso",
    "taille_conge": "Raggio", "taille_chanfrein": "Larghezza", "aretes": "Spigoli",
    "regle_toutes": "Tutti gli spigoli", "regle_haut": "Gli spigoli in alto",
    "regle_bas": "Gli spigoli in basso", "regle_verticales": "Gli spigoli verticali",
    "regle_liste": "Gli spigoli scelti", "choisir_aretes": "Scegli gli spigoli",
    "choisir_aretes_aide": "Clicca gli spigoli sul pezzo. Clicca di nuovo per toglierli.",
    "aretes_n": "{n} spigolo/i scelto/i", "termine": "Fatto",
    "err_vide": "Questo passaggio non lascia materiale.",
    "err_geometrie": "Non è stato possibile calcolare questa forma.",
    "err_rien_a_arrondir": "Non c'è ancora nulla da arrotondare: aggiungi prima una forma.",
    "err_aucune_arete": "Qui non corrisponde nessuno spigolo.",
    "err_introuvables": "Gli spigoli scelti non esistono più. Scegline di nuovi.",
    "err_trop_grand": "Troppo grande per questo pezzo.",
    "err_trop_grand_max": "Troppo grande: qui al massimo {max} mm.",
    "aretes_manquantes": "{n} spigolo/i non sono stati ritrovati.",
    "calcul": "Calcolo in corso…", "volume": "Volume {v} {u}",
    "imprimante": "Stampante: {nom}",
    "unite": "Unità", "unite_mm": "Millimetri (mm)",
    "unite_cm": "Centimetri (cm)", "unite_in": "Pollici (in)",
    "verif_ok": "Pronto per la stampa.",
    "verif_ouverte": "Il pezzo non è chiuso: la stampa fallirà.",
    "verif_trop_grande": "Troppo grande per il piano ({x} × {y} × {z} mm per {px} × {py} × {pz} mm).",
    "verif_morceaux": "Il pezzo è in {n} parti separate.",
    "verif_trop_fine": "Un dettaglio misura {mm} mm: troppo sottile per essere stampato.",
    "exporter_quand_meme": "Esporta comunque", "corriger": "Correggi",
    "avert_titre": "Prima di esportare",
    "projet_neoforge": "Progetto neoForge (*.nfg)", "fichier_stl": "File STL (*.stl)",
    "fichier_3mf": "File 3MF (*.3mf)", "fichier_step": "File STEP (*.step)",
    "enregistre": "Salvato: {nom}", "exporte": "Esportato: {nom}",
    "ouverture_impossible": "Impossibile aprire questo file.",
    "enregistrement_impossible": "Salvataggio impossibile: {err}",
    "quitter_titre": "Chiudi neoForge",
    "quitter_texte": "Il pezzo è cambiato dall'ultimo salvataggio. Salvare prima di chiudere?",
    "restaurer_titre": "Riprendi il pezzo",
    "restaurer_texte": "L'ultima volta neoForge si è chiuso all'improvviso. Riprendere il pezzo in corso?",
    "envoi_ok": "Pezzo inviato a neoSlice.", "envoi_lancement": "Apertura di neoSlice…",
    "envoi_echec": "neoSlice non ha risposto. Apri neoSlice e riprova.",
    "envoi_vide": "Non c'è nulla da inviare.",
})

LANGUES = {"fr": FR, "en": EN, "es": ES, "de": DE, "it": IT}


def T(cle: str, **kw) -> str:
    """Texte dans la langue de neoSlice (repli anglais puis français)."""
    try:
        from core.i18n import lang
        code = lang()
    except Exception:
        code = "fr"
    s = LANGUES.get(code, FR).get(cle) or EN.get(cle) or FR.get(cle, cle)
    if kw:
        try:
            return s.format(**kw)
        except (KeyError, ValueError):
            return s
    return s
